default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host:     localhost
  port:     5432
  schema_search_path: public
  min_messages: warning
development:
  <<: *default
  database: rails_react_recipe_development

test:
  <<: *default
  database: rails_react_recipe_test

production:
  <<: *default
  database: rails_react_recipe_production
  username: rails_react_recipe
  password: <%= ENV["RAILS_REACT_RECIPE_DATABASE_PASSWORD"] %>
